services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: korotish
      POSTGRES_PASSWORD: korotish
      POSTGRES_DB: korotish
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
