"""make target_url required

Revision ID: 5195660c1c19
Revises: 208066b4569a
Create Date: 2026-07-20 23:48:50.515422

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5195660c1c19"
down_revision: str | Sequence[str] | None = "208066b4569a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("links", "target_url", existing_type=sa.VARCHAR(length=2048), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("links", "target_url", existing_type=sa.VARCHAR(length=2048), nullable=True)
    # ### end Alembic commands ###
